Update zh_cn.json
wendall911/Homeostatic pull request #32
Opened 2023-07-29 09:01 UTC by DarkgreenWorld

A more accurate and fluent translation reduces the roughness, ambiguity, and misunderstandings caused by machine translation.

2023-07-29 11:11 UTC, Athurrender requested changes

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.education.desc": "本节专门针对那些试图公开论证，在又湿又冷并且只穿着T恤和裤子时通过跑来跑去可以产生足够的身体热量,的人（即使你有几分超人的能力）。 这太愚蠢了。$(br)$(br)如果需要，请参阅以下页面以了解其实际工作原理。提示：无论你跳来跳去或跑多少，如果身体又湿又冷，都会被冻死。此外，非常热的东西会烫伤、烧伤你或者把你煮
本节专门针对那些试图公开论证“在又湿又冷并且只穿着T恤和裤子时通过跑来跑去可以产生足够的身体热量”的人（即使你有几分超人的能力）。
这里建议改用引号。

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可用在合成中去过滤皮革水袋中的脏水。",
建议：滤水纸也可在合成中使用以过滤皮革水袋中的脏水。

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部环境温度的位置。可以以华氏度或摄氏度显示。",
建议：上面的箭头指向HUD中局部环境温度的位置。可以用华氏度或摄氏度显示。

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.body_temp.intro": "上面的箭头指向体温在HUD中的位置。可以华氏度或摄氏度显示。",
建议：上面的箭头指向HUD中体温的位置。可以用华氏度或摄氏度显示。
这里可以和下面一样改一下。

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.hydration.details": "补水有几种方法：$(br)$(li)徒手喝水。$(li2)蹲下并右键任何水源，你可以直接喝水。这可能会导致一个负面的状态效果。$(li)准备一个水袋。合成表和详细信息在以下页面上。$(li)吃有水分的食物或饮料。如果手持任何含水物品，一个小小的预览就会在水分条上闪烁(类似苹果皮模组)。"
建议： “这可能会产生一个负面的状态效果。” “一个小预览将会在水分条上闪烁(类似苹果皮模组)。”

2023-07-29 11:11 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "death.attack.hasHyperthermia.player": "在与 %2$s 战斗时，可怜的 %1$s 的生命被中暑夺走了",
这里用 “在与 %2$s 战斗时，中暑夺走了可怜的 %1$s 的生命” 就好吧？应该不需要搞成被动式。

2023-07-29 11:13 UTC, Athurrender commented
上次验证汉化偷懒了😥，这次稍微认真看一下。

2023-07-29 11:19 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.education.desc": "本节专门针对那些试图公开论证，在又湿又冷并且只穿着T恤和裤子时通过跑来跑去可以产生足够的身体热量,的人（即使你有几分超人的能力）。 这太愚蠢了。$(br)$(br)如果需要，请参阅以下页面以了解其实际工作原理。提示：无论你跳来跳去或跑多少，如果身体又湿又冷，都会被冻死。此外，非常热的东西会烫伤、烧伤你或者把你煮
好的，谢谢提醒

2023-07-29 11:20 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可用在合成中去过滤皮革水袋中的脏水。",
OK

2023-07-29 11:21 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部环境温度的位置。可以以华氏度或摄氏度显示。",
我考虑考虑

2023-07-29 11:22 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.hydration.details": "补水有几种方法：$(br)$(li)徒手喝水。$(li2)蹲下并右键任何水源，你可以直接喝水。这可能会导致一个负面的状态效果。$(li)准备一个水袋。合成表和详细信息在以下页面上。$(li)吃有水分的食物或饮料。如果手持任何含水物品，一个小小的预览就会在水分条上闪烁(类似苹果皮模组)。"
好的

2023-07-29 11:30 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "death.attack.hasHyperthermia.player": "在与 %2$s 战斗时，可怜的 %1$s 的生命被中暑夺走了",
搞成被动式能让"%1$s"当主语，以与前边的“战斗”相匹配，表意更明确，您再考虑考虑。

2023-07-29 11:40 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部环境温度的位置。可以以华氏度或摄氏度显示。",
这里用“以”更好，两者含义区别不大，也没必要反复更改。

2023-07-29 11:41 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "death.attack.hasHyperthermia.player": "在与 %2$s 战斗时，可怜的 %1$s 的生命被中暑夺走了",
“在与 %2$s 战斗时，可怜的 %1$s 被中暑夺走了生命”，如果用被动式就改成这样吧，语序更通顺些？

2023-07-29 11:43 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部环境温度的位置。可以以华氏度或摄氏度显示。",
这里主要是把第二个以改为用，意义相近又不会重复。

2023-07-29 11:45 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "death.attack.hasHyperthermia.player": "在与 %2$s 战斗时，可怜的 %1$s 的生命被中暑夺走了",
好的（有时候英文看多了中文语序都乱了（悲

2023-07-29 11:48 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.environment.intro": "上面的箭头指向HUD中局部环境温度的位置。可以以华氏度或摄氏度显示。",
好吧

2023-07-29 12:07 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.education.desc": "本节专门针对那些试图公开论证“在又湿又冷并且只穿着T恤和裤子时通过跑来跑去可以产生足够的身体热量”的人（即使你有几分超人的能力）。 这太愚蠢了。$(br)$(br)如果需要，请参阅以下页面以了解其实际工作原理。提示：无论你跳来跳去或跑多少，如果身体又湿又冷，都会被冻死。此外，非常热的东西会烫伤、烧伤你或者把你煮
“提示：无论你是跳来跳去还是跑了多少，如果身体又湿又冷，都会让你被冻死。”
改了一下，有没有更通顺一些？

2023-07-29 12:10 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.intro": "不违反逻辑的温度和水分变化...$(br)$(li) $(l:homeostatic:education/environment)环境$()温度受 $(l:https://simple.wikipedia.org/wiki/Thermal_radiation)热辐射$()影响, 比如太阳、岩浆、营火等等。$(li)必须保持体温，
“否则你会得到”建议去掉“得到”二字，这是机翻get的痕迹。

2023-07-29 13:12 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.education.desc": "本节专门针对那些试图公开论证“在又湿又冷并且只穿着T恤和裤子时通过跑来跑去可以产生足够的身体热量”的人（即使你有几分超人的能力）。 这太愚蠢了。$(br)$(br)如果需要，请参阅以下页面以了解其实际工作原理。提示：无论你跳来跳去或跑多少，如果身体又湿又冷，都会被冻死。此外，非常热的东西会烫伤、烧伤你或者把你煮
雀食，当时没细看

2023-07-29 13:13 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.intro": "不违反逻辑的温度和水分变化...$(br)$(li) $(l:homeostatic:education/environment)环境$()温度受 $(l:https://simple.wikipedia.org/wiki/Thermal_radiation)热辐射$()影响, 比如太阳、岩浆、营火等等。$(li)必须保持体温，
好的

2023-07-29 13:48 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可在合成中使用以过滤皮革水袋中的脏水。",
我在游戏里测试了，这一句指示的是滤水纸的合成配方，正确的翻译应该是"也可合成滤水纸以过滤皮革水袋中的脏水。"

2023-07-29 14:32 UTC, wendall911 commented
Thank you for the submission. I need to fix a few issues with 1.19.2 and supporting more mods that add biomes then I'll add this. Thanks for the contribution!

2023-07-29 15:12 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可在合成中使用以过滤皮革水袋中的脏水。",
那位老哥真的是自信啊（

2023-07-29 15:14 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.hydration.water_filter.text": "滤水纸也可在合成中使用以过滤皮革水袋中的脏水。",
已经根据您的建议完成了修正

2023-07-29 15:43 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
> +  "info.homeostatic.book.gameplay.body_temp.details": "有几个因素用于计算体温:$(br)$(li)环境温度.$(li)盔甲 - 详情见后页.$(li2)$(l:homeostatic:gameplay/body_temp#insulation)保暖$()$(li2)$(l:homeostatic:gameplay/body_temp#rad
有几个因素用于计算体温:$(br)$(li)环境温度。$(li)盔甲 - 详情见后页。
玩家的干湿程度决定了他们降温或升温的速度。
使用了英文句号，改为了中文。

2023-07-29 15:45 UTC, Athurrender requested changes

2023-07-29 15:45 UTC, Athurrender commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.body_temp.wetness.details": "玩家的干湿程度决定了 $(l:homeostatic:gameplay/body_temp)体温$() 降低的速度. 这可能是好事也可能是坏事，视情况而定:$(li)炎热时，潮湿或在水中可以帮助玩家快速降温。$(li)寒冷时，潮湿会增加玩家冻死的风险。$(li2)寻找庇护
玩家的干湿程度决定了 $(l:homeostatic:gameplay/body_temp)体温$() 降低的速度。
同改为中文句号，这下应该完全没有问题了。

2023-07-30 05:44 UTC, DarkgreenWorld commented on src/main/resources/assets/homeostatic/lang/zh_cn.json
>    "info.homeostatic.book.gameplay.body_temp.wetness.details": "玩家的干湿程度决定了 $(l:homeostatic:gameplay/body_temp)体温$() 降低的速度. 这可能是好事也可能是坏事，视情况而定:$(li)炎热时，潮湿或在水中可以帮助玩家快速降温。$(li)寒冷时，潮湿会增加玩家冻死的风险。$(li2)寻找庇护
感谢您的细致审核

2023-07-30 05:59 UTC, DarkgreenWorld commented
解决了，请您查看

2023-07-30 08:56 UTC, Athurrender approved these changes
可以了，还有一两句感觉可改可不改，还是不麻烦了😂

2023-07-30 14:11 UTC, wendall911 commented
I should be able to work on this later. I worked on adding support for more modded biomes yesterday. I have a release up on Modrinth for it now, but still waiting on CurseForge to fix a bug in their scanner to do a release there.

2023-07-30 19:39 UTC, merged

2023-07-30 20:08 UTC, wendall911 commented
CurseForge is having some issues with their Malware processor. I'm working with support on this, so could take a bit before this is available there. In the meanwhile, builds with the latest translation are up on Modrinth: https://modrinth.com/mod/homeostatic